### ISSUE TITLE
Spotify Error

### ISSUE THREAD

**Issue by dadede** [hbashton/spotify-ripper#1]
Spotify error detected
unsupported operand type(s) for +: 'bool' and 'unicode'
Skipping to next track...
Deleting partially ripped file

seems there's a bug somewhere when downloading playlists... any suggestions?

**Comment by hbashton** [comment]
It worked for me. Sorry.

**Comment by dadede** [comment]
figured the cause of the error. turns out that when it tries to append the genre metadata after it has finished ripping to file, something goes wrong somewhere with the variables. don't know enough python to figure it out, but its worth a check if the genre feature will be stable - just saying. and great job!

**temporary fix - avoid adding genre**
