### ISSUE TITLE
Timeout with large playlist

### ISSUE THREAD

**Issue by giann** [hbashton/spotify-ripper#10]
If the playlist being ripped is about more than 100 songs, it will go into timeout

**Comment by riki137** [comment]
I believe recreating the playlist fixes the issue. (Ctrl+A, Ctrl+C, Ctrl+V) and that amount of songs is not a factor.

**Comment by mrmicheall** [comment]
Didn't fix it for me. Recreated a playlist as my own, still timeout. Cut the number of tracks on my playlist down to 25, still timed out.

updated pyspotify-2.0.5-py2.7-linux-x86_64.egg/spotify/utils.py so the timeout is 120s, still times out.

Edit 1: 
With timeout set to 120s, I tried to rip a playlist with 1 track on it, timed out. Could rip the song specifically though with the song's URI, though not with the playlist URI

Edit 2:
The same song also ripped fine when using the album URI.

**Comment by mrmicheall** [comment]
Looking further around it appears that Spotify has done something with playlists. Mopidy is suffering from playlist errors as well: https://github.com/mopidy/mopidy-spotify/issues/133
