### ISSUE TITLE
Can you add the tempo or bpm to flac ?

### ISSUE THREAD

**Issue by Pancho111** [hbashton/spotify-ripper#11]
HI, 
Can you add the tempo or bpm to flac ?

{
  "danceability" : 0.596,
  "energy" : 0.869,
  "key" : 10,
  "loudness" : -11.970,
  "mode" : 1,
  "speechiness" : 0.0370,
  "acousticness" : 0.0116,
  "instrumentalness" : 0.173,
  "liveness" : 0.0678,
  "valence" : 0.949,
  "tempo" : 109.902,
  "type" : "audio_features",
  "id" : "05wIrZSwuaVWhcv5FfqeH0",
  "uri" : "spotify:track:05wIrZSwuaVWhcv5FfqeH0",
  "track_href" : "https://api.spotify.com/v1/tracks/05wIrZSwuaVWhcv5FfqeH0",
  "analysis_url" : "https://api.spotify.com/v1/audio-analysis/05wIrZSwuaVWhcv5FfqeH0",
  "duration_ms" : 238733,
  "time_signature" : 4
}

Thanks

**Comment by hbashton** [comment]
I can always try. Give me a little time to take a look.
