### ISSUE TITLE
Problems with spotify-ripper and pyenv versions? Pyspotify?

### ISSUE THREAD

**Issue by Kezzsim** [hbashton/spotify-ripper#17]
Hello again, I have this all working well on my macbook- trying to install it on a Mac Pro I found and updated to El Capitan recently. Everything was going well up until I tried to run the program, which results in the following traceback:

`Traceback (most recent call last):
  File "/Users/karibarry/.pyenv/versions/2.7.10/bin/spotify-ripper", line 9, in <module>
    load_entry_point('spotify-ripper==2.9.1', 'console_scripts', 'spotify-ripper')()
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/karibarry/.pyenv/versions/2.7.10/bin/main.py", line 4, in <module>
    __import__('pkg_resources').run_script('spotify-ripper==2.9.1', 'main.py')
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1642, in run_script
    exec(code, namespace, namespace)
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper-2.9.1-py2.7.egg/EGG-INFO/scripts/main.py", line 7, in <module>
    from spotify_ripper.ripper import Ripper
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper-2.9.1-py2.7.egg/spotify_ripper/ripper.py", line 9, in <module>
    from spotify_ripper.progress import Progress
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/spotify_ripper-2.9.1-py2.7.egg/spotify_ripper/progress.py", line 11, in <module>
    import spotify
  File "/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pyspotify-2.0.5-py2.7-macosx-10.11-x86_64.egg/spotify/__init__.py", line 81, in <module>
    from spotify._spotify import ffi, lib  # noqa
ImportError: dlopen(/Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pyspotify-2.0.5-py2.7-macosx-10.11-x86_64.egg/spotify/_spotify.so, 2): Library not loaded: @loader_path/../Frameworks/libspotify.framework/libspotify
  Referenced from: /Users/karibarry/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pyspotify-2.0.5-py2.7-macosx-10.11-x86_64.egg/spotify/_spotify.so
  Reason: image not found`

I'm not intimately familiar with the code here but I think it's telling me there's some sort of problem with pyenv's version; this happened the first time I tried to run and I put in version 3.5. After that didn't work I `sudo rm -rf ~/.pyenv/versions/3.5.0` and tried again with 2.7.10 like in the install guide.

Someone could probably easily see what's going on here, sadly I can't.

Thanks!

**Comment by ramonskie** [comment]
it seems to me that libspotify is not installed/loaded

**Comment by Kezzsim** [comment]
Right, and apparently I can't brew install it from it's original formula. Is there anything special I need to do to the mopidy/mopidy/libspotify install to make it recognize it? I've tried re-making the link to the dylib several times with no luck.

**Comment by Kezzsim** [comment]
Nevermind, I just had to completely clean out my .pyenv folder, and I started using [this slightly updated version](https://github.com/SolidHal/spotify-ripper) instead which installs over pip (which I find easier to manage than homebrew for some reason) . It's all good now~

**Comment by Pancho111** [comment]
Hi Kezzsim , is that version doing the coverart ?
My coverart is empty , can you please verify?
thanks

**Comment by Kezzsim** [comment]
Now that you mention it, my cover art is also empty... 😮
Just noticed that today.

Is there a Web-API alternative to this program yet? It's absolutely ancient and I'm surprised it didn't stop working a long time ago altogether! I've been lamenting that my Account and LibSpot keys are tied to my Facebook account, which I've been longing to delete over the past few months. (I also use my LibSpot keys for listening on older embedded stereos)
I'm not surprised things have been like this lately, when I was applying to work there I noticed they were hiring a lot of fraud, loss prevention people each with their own six figure salary, they aren't gonna be sitting on their asses all day doing nothing.

**Comment by seandex** [comment]
> Now that you mention it, my cover art is also empty... 😮
> Just noticed that today.
> 
> Is there a Web-API alternative to this program yet? It's absolutely ancient and I'm surprised it didn't stop working a long time ago altogether! I've been lamenting that my Account and LibSpot keys are tied to my Facebook account, which I've been longing to delete over the past few months. (I also use my LibSpot keys for listening on older embedded stereos)
> I'm not surprised things have been like this lately, when I was applying to work there I noticed they were hiring a lot of fraud, loss prevention people each with their own six figure salary, they aren't gonna be sitting on their asses all day doing nothing.

Hi.. Did you find the solution? I need cover art soo bad.

**Comment by Kezzsim** [comment]
Nothing automatic just yet but I have found this which works quite nice with the WebAPI key required for getting playlists : https://github.com/yashhere/BeautifyMP3

**Comment by Kezzsim** [comment]
6 months later for those of you wanting an all encompassing solution:
@pauloup resolved the album art issue so you can run `git clone https://github.com/pauloup/spotify-ripper.git` and then `git checkout fixcoverart` to get to a place where you can build a fully working version with `sudo python setup.py install` (Might need to use pip to install `urllib3`)

If you're starting from scratch (on MacOS) check out [https://github.com/Kezzsim/homebrew-libspotify](https://github.com/Kezzsim/homebrew-libspotify) which you can install with `brew install ./libspotify.rb` to set up most of the prerequisites. I'm glad this is still working well in 2019 🤞
