### ISSUE TITLE
Song quality doesn't match

### ISSUE THREAD

**Issue by C0N71** [hbashton/spotify-ripper#27]
I just want to know this: i set in the file config.ini the quality to rip at 320, but when i rip a song the kbps is't 320, but lower, sometimes 272, 266, 262 etc..., i just want to know if this is a spotify ripper issue or if i wrong something to set, or maybe is that spotify doesn't have the songs at the highest quality, but lower, to save storage in their server or i don't no, other reason (?)

**Comment by cvanderwall14** [comment]
Same thing happens to me. Haven't looked into it closely, but I'm wondering if Spotify just doesn't always send full 320 kbps even if you request it.

**Comment by thenewnano** [comment]
If you use joint stereo it compresses in the bitrate needed not 320. Change to standard stereo and try , quality out should be the same though .

**Comment by C0N71** [comment]
ok thx i'll try, anyway there are different options for stereo mode:  "--stereo-mode {j,s,f,d,m,l,r} Advanced stereo settings for Lame MP3 encoder only", which from the j, s, f, d, m, l and r options is the standard one and which is the meaning of these option if you know?

**Comment by hail0** [comment]
@C0N71 
Which solution did you pick in the meanwhile?

**Comment by C0N71** [comment]
Well, I recorded a song to see the difference and these are the results:
Stereo mode {j} -> 253 kbps Joint-Stereo
Stereo mode {s} -> 252 kbps Stereo
Stereo mode {f} -> 274 kbps Joint-Stereo
Stereo mode {d} -> 251 kbps Dual-Channel
Stereo mode {m, l}  -> 143 kbps mono ('m' is real mono, in 'l' I listened the song a little clipped}
Stereo mode {r} -> 31 kbps mono (i can say "mute", nothing recorded)

**Comment by C0N71** [comment]
I think the only way to record at 320kbps is ripping in ogg vorbis format with the command --vorbis, i tested it and the result was a 320 kbps audio file in stereo

**Comment by C0N71** [comment]
I did others experiment, to record mp3 in stereo mode and at 320 you need to add these command: --stereo-mode s -c
-c stand for cbr, the default bitrate is 320, but you can change typing -b {quality}
