### ISSUE TITLE
pip no longer hosts spotify-ripper

### ISSUE THREAD

**Issue by Kezzsim** [hbashton/spotify-ripper#3]
Hey um, I'm super glad you decided to revive this project; up until now I had been putting off experimenting with it until a rainy day. Unfortunately, now that that rainy day has come it looks like Spotify has gone for the jugular and torched all the pip repositories that this project relies upon:

https://pypi.python.org/pypi/spotify-ripper/2.10.3
and
https://pypi.python.org/pypi/spotify-ripper/1.4.1
are totally gone and `pip install spotify-ripper` does absolutely nothing.

Is there any place I can find the script here on the github? I apologize but python isn't really a strong point of mine; I'd really appreciate good instruction.

Thank you for taking on this project!

**Comment by celson** [comment]
Hi Kezzsim,

try `pip install spotify-ripper-morgaroth`.

I hope to help you.

Regards,
Celson Simon

**Comment by Kezzsim** [comment]
Hi Celson!
That worked! Someone should update the read me with that pip link!

Thank you~
Kezzsim
