### ISSUE TITLE
libspotify-12.1.15 not available through spotify anymore

### ISSUE THREAD

**Issue by lavolp3** [hbashton/spotify-ripper#39]
`wget https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz`
results in a 404 error. A file is downloaded but not extractable.

`--2018-10-08 15:07:20--  https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz
Resolving developer.spotify.com (developer.spotify.com)... 151.101.14.133
Connecting to developer.spotify.com (developer.spotify.com)|151.101.14.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://developer.spotify.com/404.html [following]
--2018-10-08 15:07:21--  https://developer.spotify.com/404.html
Reusing existing connection to developer.spotify.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 98090 (96K) [text/html]
Saving to: ‘libspotify-12.1.51-Linux-x86_64-release.tar.gz’

libspotify-12.1.51-Linux-x86_64-r 100%[===========================================================>]  95.79K  --.-KB/s    in 0.02s

2018-10-08 15:07:21 (3.92 MB/s) - ‘libspotify-12.1.51-Linux-x86_64-release.tar.gz’ saved [98090/98090]
`
System: 
Raspberry Pi 3B+ running Raspbian Stretch
Python 2.7.13

Might be possible to use [mopidy's libspotify](https://github.com/mopidy/libspotify-deb) instead?

**Comment by lavolp3** [comment]
FTWC I have made a fork and sent a Pull Request editing the Readme with a walkaround for this issue.

**Comment by StephanX** [comment]
Looks like it can be found here: https://github.com/mopidy/libspotify-archive

**Comment by lavolp3** [comment]
@StephanX thanks for the hint.
For now I have integrated the current mopidy libspotify in my [forked repo](https://github.com/lavolp3/spotify-ripper) and it works
Closing it now. PR is still open
