### ISSUE TITLE
Windows 10 Question...

### ISSUE THREAD

**Issue by jonaaa20** [hbashton/spotify-ripper#4]
Is there any way to make it work on Windows 10, i know that Windows 10 have a Ubuntu Bash System so... is there any way to make it work?

**Comment by hbashton** [comment]
No there is NOT a way to do such a thing. Reason being libspotify does NOT
work on windows. I am sorry to say that this is 100% impossible, but i
would recommend you google search "virtualbox" to run ubuntu on windows

**Comment by jonaaa20** [comment]
There's a way to use it on windows but the tutorial was on jrnewell git, that's sad... but i will install ubuntu on virtualbox, thanks.
