### ISSUE TITLE
pyspotify installation fails with setup.py

### ISSUE THREAD

**Issue by lavolp3** [hbashton/spotify-ripper#40]
`Searching for pyspotify==2.0.5
Reading https://pypi.python.org/simple/pyspotify/
Downloading https://files.pythonhosted.org/packages/5b/ce/7a6520ea348023762d5b138e85809198626c758ee8053bfc534438ad8bad/pyspotify-2.0.5.tar.gz#sha256=fbd41c58d62232b0cabb7a9e38d45f36ac221699c006899bdb6be74c04602678
Best match: pyspotify 2.0.5
Processing pyspotify-2.0.5.tar.gz
Writing /tmp/easy_install-9lFZzw/pyspotify-2.0.5/setup.cfg
Running pyspotify-2.0.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9lFZzw/pyspotify-2.0.5/egg-dist-tmp-Iurqyp
c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1`

Reason may be the python version I'm using (2.7.13) since 2.7.10 cannot be installed via pyenv on Debian Scratch.

However a solution is to use [mopidy's repository](https://github.com/mopidy/libspotify-deb) and install python-spotify from there.
After that, setup.py install went thorugh without an error.
I'll try to create a PR. (Not common in github)

**Comment by lavolp3** [comment]
FTWC I have made a fork and sent a Pull Request editing the Readme with a walkaround for this issue.

**Comment by ghost** [comment]
Installing python-dev & python-setuptools can help with this.
