### ISSUE TITLE
Fail to grab and embed a cover

### ISSUE THREAD

**Issue by reardenlife** [hbashton/spotify-ripper#45]
Here is an output of freshly ripped file:

```text
$ eyeD3 Hot\ Boys/Guerrilla\ Warfare/Hot\ Boys\ -\ You\ Dig.mp3
eyed3.core:WARNING: APIC frame does not contain image data/url
.../aria2/order1/Hot Boys/Guerrilla Warfare/Hot Boys - You Dig.mp3[ 7.70 MB ]
------------------------------------------------------------------------Time: 03:58     MPEG1, Layer III        [ ~271 kb/s @ 44100 Hz - Joint stereo ]
------------------------------------------------------------------------ID3 v2.4:
title: You Dig
artist: Hot Boys
album: Guerrilla Warfare
recording date: 1999
track: 11/17
disc: 1/1
FRONT_COVER Image: [Size: 0 bytes] [Type: image/jpeg]
Description: Front Cover
```

As can be seen, the inserted coverart is zero bytes long.
I wonder why it fails to get and embed the cover.  Did anyone got a similar issue?

**Comment by reardenlife** [comment]
So no one got the sources of the libspotify I assume?
In the meantime, I wrote this:

```bash
#!/usr/bin/env bash

set -e
set -o errexit

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

token="${1}"
trackid="${2}"

t=$(curl -X GET "https://api.spotify.com/v1/tracks/$trackid" -H "Authorization: Bearer $token" )
url=$(echo "$t" | jq -r '.album' | jq -r '.images[1]' | jq -r '.url')
A=$(echo "$t" | jq -r '.album' | jq -r '.name')
a=$(echo "$t" | jq -r '.artists[0]' | jq -r '.name')
path="$a"/"$A"/cover.jpg
if [ ! -f "$path" ]; then
  wget -nc "$url" -O "$path"
fi
```

**Comment by reardenlife** [comment]
I wonder why this project doesn't use opensource library to deal with Spotify.  For example, here: https://github.com/plietar/librespot-1/blob/master/README.md

**Comment by reardenlife** [comment]
And why its ever suppose to be simple, huh?

Well, the problem is that the ripper is preprocessing artist and album fields before using them.  Meaning that I have to do the same to get the path to the folder to save the cover.jpg.

Updated code follows:

```bash
#!/usr/bin/env bash

set -e
set -o errexit

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

token="${1}"
trackid="${2}"

t=$(curl -X GET "https://api.spotify.com/v1/tracks/$trackid" -H "Authorization: Bearer $token" )
url=$(echo "$t" | jq -r '.album' | jq -r '.images[1]' | jq -r '.url')
A=$(echo "$t" | jq -r '.album' | jq -r '.name')
a=$(echo "$t" | jq -r '.album' | jq -r '.artists[0]' | jq -r '.name')

a=${a%%.}
A=$(echo "$A" | tr ':' -d)

path="$a"/"$A"/cover.jpg
echo "$trackid:'$url'   --->   '$path'"
if [ ! -f "$path" ]; then
  echo "Downloading.."
  wget -nc "$url" -O "$path"
fi
```

Can anyone point out where spotify-ripper does the preprocessing?

**Comment by reardenlife** [comment]
Alright.  Lets try again...

```bash
#!/usr/bin/env bash

set -e
set -o errexit

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

token="${1}"
trackid="${2}"

t=$(curl -X GET "https://api.spotify.com/v1/tracks/$trackid" -H "Authorization: Bearer $token" )
url=$(echo "$t" | jq -r '.album' | jq -r '.images[1]' | jq -r '.url')
A=$(echo "$t" | jq -r '.album' | jq -r '.name')
a=$(echo "$t" | jq -r '.album' | jq -r '.artists[0]' | jq -r '.name')
a2=$(echo "$t" | jq -r '.artists[0]' | jq -r '.name')

a=${a%%.}
a2=${a2%%.}
A1=$(echo "$A" | sed 's/://g')
A2=$(echo "$A" | sed 's/://g' | sed 's/-//g')

dir=()
dir+=("$a"/"$A1")
dir+=("$a"/"$A2")
dir+=("$a2"/"$A1")
dir+=("$a2"/"$A2")
path=""
for d in "${dir[@]}"; do
  if [ ! -d "$d" ]; then
    echo "WARN: Directory '$d' doesn't exist."
  else
    path="$d"/cover.jpg
    break
  fi
done
if [ ! -d "$d" ]; then
  echo "ERR: Failed to find a destination dir for the cover ($a:$a2::$A)."
  exit 1
fi
echo "$trackid:'$url'   --->   '$path'"
if [ ! -f "$path" ]; then
  echo "Downloading.."
  wget -nc "$url" -O "$path"
fi
```

Can anyone propose a better solution?

**Comment by reardenlife** [comment]
Multiple artists support:

<b>Edited:</b>

```sh
cat spotify-hlp-get-covers.sh
#!/usr/bin/env bash

set -e
set -o errexit

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

token="${1}"
trackid="${2}"

t=$(curl -X GET "https://api.spotify.com/v1/tracks/$trackid" -H "Authorization: Bearer $token" )
url=$(echo "$t" | jq -r '.album' | jq -r '.images[1]' | jq -r '.url')
A=$(echo "$t" | jq -r '.album' | jq -r '.name')

aa=()
c=$(echo "$t" | jq -r '.album' | jq -r '.artists | length')
for i in $(seq 1 $c); do
  indx=($i-1)
  a=$(echo "$t" | jq -r '.album' | jq -r ".artists[$indx]" | jq -r '.name')
  aa+=("$a")
done
c=$(echo "$t" | jq -r '.artists | length')
for i in $(seq 1 $c); do
  indx=($i-1)
  a=$(echo "$t" | jq -r ".artists[$indx]" | jq -r '.name')
  aa+=("$a")
done

for a in "${aa[@]}"; do
  echo "$a:$A"
  a=${a%%.}
  A=${A%%.}
  A1=$(echo "$A" | sed 's/://g' | sed 's/*//g' | sed -E 's/\.\.+/\./g' )
  A2=$(echo "$A1" | sed 's/-//g')

  dir=()
  dir+=("$a"/"$A1")
  dir+=("$a"/"$A2")
  path=""
  for d in "${dir[@]}"; do
    if [ ! -d "$d" ]; then
      echo "WARN: Directory '$d' doesn't exist."
    else
      path="$d"/cover.jpg
      break
    fi
  done
  if [ ! -d "$d" ]; then
    echo "ERR: Failed to find a destination dir for the cover ($a:$a2::$A)."
    #exit 1
  else
    echo "$trackid:'$url'   --->   '$path'"
    if [ ! -f "$path" ]; then
      echo "Downloading.."
      wget -nc "$url" -O "$path"
    fi
  fi
done
```

**Comment by freuz** [comment]
hi,
could any of you please describe how to use the scripts above for a person not so educated in linux etc.
specific: what should i enter in the script, like my appkey (how) etc
thanks in advance :)

**Comment by reardenlife** [comment]
@freuz,
Well, as you can see, the script's input parameters are: token ans track id.

I have a different script to download all the covers for the playlist I ripped.  Here:

```bash
[root@v48807 aria2]# cat spotify-get-covers.sh
#!/usr/bin/env bash

set -e
set -o errexit

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

CID=$(cat "${1}" | jq -r '.CID')
CS=$(cat "${1}" | jq -r '.CS')

auth=$(echo -n "$CID:$CS" | base64 -w 0)

t=$(curl -X "POST" -H "Authorization: Basic $auth" -d grant_type=client_credentials https://accounts.spotify.com/api/token)
token=$(echo "$t" | jq -r '.access_token')

playlisturl="${2}"
user=$(echo $playlisturl | cut -d "/" -f5)
uri=$(echo $playlisturl  | cut -d "/" -f7 | cut -d "?" -f1)

offset=0
tracks=""
while (( $offset < 42000 )); do
  t=$(curl "https://api.spotify.com/v1/users/$user/playlists/$uri/tracks?fields=items(track(uri))&offset=$offset" -H "Authorization: Bearer $token" )
  ctracks="$(echo "$t" | jq -r '.items[] | .track | .uri' )"
  tracks="$tracks$ctracks"
  if [ -z "$ctracks" ]; then
    break
  fi
  offset=$((offset+100))
done

cnt=$(echo "$tracks" | wc -l)
echo "Got $cnt tracks"
echo "$tracks" | xargs -L1 | cut -d ":" -f3 | xargs -L1 bash "$DIR"/spotify-hlp-get-covers.sh "$token"
```

**Comment by reardenlife** [comment]
@freuz,

Anyways,  it is better to start now than never. :)

https://nostarch.com/tlcl

**Comment by durandom** [comment]
same here. for what it's worth:
[here](https://github.com/hbashton/spotify-ripper/blob/d0464193dead7bd3ac7580e98bde86a0f323acae/spotify_ripper/tags.py#L72) the cover obj get's instantiated and this is part of [libspotify](https://developer.spotify.com/technologies/libspotify/) which is no more. So we're stuck with a binary blob. The [python binding](https://github.com/mopidy/pyspotify) shows that we can pass [some args](https://github.com/mopidy/pyspotify/blob/851c622e814dee59362d27d978251bd3891c59f7/docs/quickstart.rst#downloading-cover-art) to `album.cover()` - see [here](https://github.com/mopidy/pyspotify/blob/851c622e814dee59362d27d978251bd3891c59f7/spotify/album.py#L103)

maybe it's just some sizes are not supported by the API anymore, maybe something more fundamental changed.

**Comment by Pancho111** [comment]
HI , I have an apple macbook pro , where should I insert the fix ?
thanks in advance

**Comment by durandom** [comment]
@Pancho111 do you have a floppy drive? This should do: 💾

**Comment by Pancho111** [comment]
Thank you for your response ,but I don't have a floppy sorry .

**Comment by Pancho111** [comment]
> 
> 
> @Pancho111 do you have a floppy drive? This should do: 💾

Hi Durandom , I don't have one 
also the little floppy ico does not have info , it is not downloadable I think 
can you please help me with this ?
thanks

**Comment by durandom** [comment]
@reardenlife I did some more research.

[here](https://github.com/hbashton/spotify-ripper/pull/2/commits/f87e83f7e7ca3f54277072be00b38dff7f7b92f1#diff-4180000773dd2725bb6da3fcfdfb74edR78) is a stale PR that add `ripper.web.get_large_coverart` which seems to download the cover via http and not via the library. That might still work.

Another approach would be to add some code from https://github.com/ritiek/spotify-downloader - this basically rips songs from youtube, but the metadata is coming from spotify

**Comment by durandom** [comment]
@reardenlife this fork: https://github.com/lilmike/spotify-ripper has the stale PR merged. Maybe it's worth trying this fork out and see if the `large-cover` option works

**Comment by Pancho111** [comment]
Thank you Durandom , I will try it and let you know .
If you find one that works just let me know .
thanks

**Comment by Pancho111** [comment]
> hi,
> could any of you please describe how to use the scripts above for a person not so educated in linux etc.
> specific: what should i enter in the script, like my appkey (how) etc
> thanks in advance :)

Hi Freuz , 
Did you find where to put the script above ? I also need to know how to do it , I don't know too much about coding , but with some instructions I could do it .
thanks

**Comment by Pancho111** [comment]
> Multiple artists support:
> 
> Edited:
> 
> ```shell
> cat spotify-hlp-get-covers.sh
> #!/usr/bin/env bash
> 
> set -e
> set -o errexit
> 
> DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
> 
> token="${1}"
> trackid="${2}"
> 
> t=$(curl -X GET "https://api.spotify.com/v1/tracks/$trackid" -H "Authorization: Bearer $token" )
> url=$(echo "$t" | jq -r '.album' | jq -r '.images[1]' | jq -r '.url')
> A=$(echo "$t" | jq -r '.album' | jq -r '.name')
> 
> aa=()
> c=$(echo "$t" | jq -r '.album' | jq -r '.artists | length')
> for i in $(seq 1 $c); do
>   indx=($i-1)
>   a=$(echo "$t" | jq -r '.album' | jq -r ".artists[$indx]" | jq -r '.name')
>   aa+=("$a")
> done
> c=$(echo "$t" | jq -r '.artists | length')
> for i in $(seq 1 $c); do
>   indx=($i-1)
>   a=$(echo "$t" | jq -r ".artists[$indx]" | jq -r '.name')
>   aa+=("$a")
> done
> 
> for a in "${aa[@]}"; do
>   echo "$a:$A"
>   a=${a%%.}
>   A=${A%%.}
>   A1=$(echo "$A" | sed 's/://g' | sed 's/*//g' | sed -E 's/\.\.+/\./g' )
>   A2=$(echo "$A1" | sed 's/-//g')
> 
>   dir=()
>   dir+=("$a"/"$A1")
>   dir+=("$a"/"$A2")
>   path=""
>   for d in "${dir[@]}"; do
>     if [ ! -d "$d" ]; then
>       echo "WARN: Directory '$d' doesn't exist."
>     else
>       path="$d"/cover.jpg
>       break
>     fi
>   done
>   if [ ! -d "$d" ]; then
>     echo "ERR: Failed to find a destination dir for the cover ($a:$a2::$A)."
>     #exit 1
>   else
>     echo "$trackid:'$url'   --->   '$path'"
>     if [ ! -f "$path" ]; then
>       echo "Downloading.."
>       wget -nc "$url" -O "$path"
>     fi
>   fi
> done
> ```

Hi reardenlife , 
How can I include the script you created in the ripper ? Thanks

**Comment by freuz** [comment]
no, i didn't understand how to use the script - just got error msg.  I think one need to be at a higher level to discuss things here, unfortunately i'm not, even though i'm not a complete noob :)

**Comment by reardenlife** [comment]
@freuz

You did recognize that spotify-get-covers.sh has two arguments. First is a path to config like that:

```json
{
  "CID": "client id",
  "CS": "client secret",
  "U": "username",
  "P": "password"                                                                       }
```

and the second is a playlist URL.

Right?

**Comment by Pancho111** [comment]
> @freuz
> 
> You did recognize that spotify-get-covers.sh has two arguments. First is a path to config like that:
> 
> ```json
> {
>   "CID": "client id",
>   "CS": "client secret",
>   "U": "username",
>   "P": "password"                                                                       }
> ```
> 
> and the second is a playlist URL.
> 
> Right?

Reardenlife , I already have the script working ,My question is 
how can I add your script without messing with the rest of the application ?
I don't want the rest to stop I just want to fix the cover issue
I have a macbook pro 
thanks

**Comment by Pancho111** [comment]
> Alright. Lets try again...
> 
> ```shell
> #!/usr/bin/env bash
> 
> set -e
> set -o errexit
> 
> DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
> 
> token="${1}"
> trackid="${2}"
> 
> t=$(curl -X GET "https://api.spotify.com/v1/tracks/$trackid" -H "Authorization: Bearer $token" )
> url=$(echo "$t" | jq -r '.album' | jq -r '.images[1]' | jq -r '.url')
> A=$(echo "$t" | jq -r '.album' | jq -r '.name')
> a=$(echo "$t" | jq -r '.album' | jq -r '.artists[0]' | jq -r '.name')
> a2=$(echo "$t" | jq -r '.artists[0]' | jq -r '.name')
> 
> a=${a%%.}
> a2=${a2%%.}
> A1=$(echo "$A" | sed 's/://g')
> A2=$(echo "$A" | sed 's/://g' | sed 's/-//g')
> 
> dir=()
> dir+=("$a"/"$A1")
> dir+=("$a"/"$A2")
> dir+=("$a2"/"$A1")
> dir+=("$a2"/"$A2")
> path=""
> for d in "${dir[@]}"; do
>   if [ ! -d "$d" ]; then
>     echo "WARN: Directory '$d' doesn't exist."
>   else
>     path="$d"/cover.jpg
>     break
>   fi
> done
> if [ ! -d "$d" ]; then
>   echo "ERR: Failed to find a destination dir for the cover ($a:$a2::$A)."
>   exit 1
> fi
> echo "$trackid:'$url'   --->   '$path'"
> if [ ! -f "$path" ]; then
>   echo "Downloading.."
>   wget -nc "$url" -O "$path"
> fi
> ```
> 
> Can anyone propose a better solution?

Reardenlife , I already have the script working ,My question is
how can I add your script without messing with the rest of the application ?
I don't want the rest to stop I just want to fix the cover issue
I have a macbook pro
thanks

**Comment by seandex** [comment]
cover art used to work fine back in the days with jrnewell's git 
after spending countless days this shit pissin me off

**Comment by reardenlife** [comment]
@Pancho111
> "I have a macbook pro"

Oh yeah? You should've said that before!  I think I know why your application keeps messing up.
The problem might be related to absense of adequate cooling in your computer, so some of the chips expanding and dislocating. It was written extensively here:
https://www.tekrevue.com/apple-iii-drop/

The only solution is to lift our computer a few feet up and drop it, so the chips will lodge in place again.

**Comment by Pancho111** [comment]
Pleeeeaaaassseee, can anybody is willing to help ?
It shouldn't be so difficult for the team in here .
Thanks

**Comment by Pancho111** [comment]
> @freuz
> 
> You did recognize that spotify-get-covers.sh has two arguments. First is a path to config like that:
> 
> ```json
> {
>   "CID": "client id",
>   "CS": "client secret",
>   "U": "username",
>   "P": "password"                                                                       }
> ```
> 
> and the second is a playlist URL.
> 
> Right?

reardenlife, where should I include the script ?
should I put it in the spotify-ripper folder ?
Thanks

**Comment by reardenlife** [comment]
@Pancho111

I provided two bash scripts:
1.) spotify-get-covers.sh
2.) spotify-hlp-get-covers.sh

So you are going to the folder where spotify ripper dumped all the music and calling the script like this:

```sh
./path/to/the/script/spotify-get-covers.sh /path/to/config/config.json https://spotify.com/path-to-your-earlier-dumped-playlist
```

spotify-hlp-get-covers.sh should lie in the same folder as spotify-get-covers.sh
How config.json should look like I already described.  For your purposes it will suffice to provide only two first parameters.

Once script is done, you should see cover.jpg in every folder with your ripped music.  So you can easily embed it with a tool like eyeD3.

> "should I put it in the spotify-ripper folder ?"

Put it anywhere you like.  It is absolutely independed of spotify-ripper.

**Comment by Pancho111** [comment]
> @Pancho111
> 
> I provided two bash scripts:
> 1.) spotify-get-covers.sh
> 2.) spotify-hlp-get-covers.sh
> 
> So you are going to the folder where spotify ripper dumped all the music and calling the script like this:
> 
> ```shell
> ./path/to/the/script/spotify-get-covers.sh /path/to/config/config.json https://spotify.com/path-to-your-earlier-dumped-playlist
> ```
> 
> spotify-hlp-get-covers.sh should lie in the same folder as spotify-get-covers.sh
> How config.json should look like I already described. For your purposes it will suffice to provide only two first parameters.
> 
> Once script is done, you should see cover.jpg in every folder with your ripped music. So you can easily embed it with a tool like eyeD3.
> 
> > "should I put it in the spotify-ripper folder ?"
> 
> Put it anywhere you like. It is absolutely independed of spotify-ripper.

Hi Reardenlife, 
I am using a Macbook pro 
I did it like this 

./Users/Panchovilla/Desktop/Music/spotify-get-covers.sh /Users/Panchovilla/Desktop/Music/config.json https://open.spotify.com/album/2quc1AEPiMFVaXllAioArj


and I am getting this error
Last login: Sun Mar 31 22:12:50 on ttys002
panchos-MacBook-Pro:~ panchovilla$ ./Users/panchovilla/Desktop/Music/spotify-get-covers.sh /Users/panchovilla/Desktop/Music/config.json https://open.spotify.com/album/2quc1AEPiMFVaXllAioArj
-bash: ./Users/panchovilla/Desktop/Music/spotify-get-covers.sh: No such file or directory
panchos-MacBook-Pro:~ panchovilla$ 

any help will be appreciated

Thanks

**Comment by reardenlife** [comment]
@Pancho111

Pretty self-explanatory, isn't it? You haven't dumped the script I posted.  It just don't exist.

You do realize that you also have to setup spotify-ripper and have premium Spotify account.  (to actually grab the music)  Right?

**Comment by Pancho111** [comment]
> @Pancho111
> 
> Pretty self-explanatory, isn't it? You haven't dumped the script I posted. It just don't exist.
> 
> You do realize that you also have to setup spotify-ripper and have premium Spotify account. (to actually grab the music) Right?

Reardenlife , 
I do have a premium account and spotify-ripper 
here are the 3 files can you please check them for me please ?



<img width="608" alt="Screen Shot 2019-03-31 at 10 59 19 PM" src="https://user-images.githubusercontent.com/19575682/55301146-095c6600-5409-11e9-9f67-d4661522922e.png">
<img width="615" alt="Screen Shot 2019-03-31 at 11 00 04 PM" src="https://user-images.githubusercontent.com/19575682/55301149-0c575680-5409-11e9-8e48-e683d976a336.png">
<img width="609" alt="Screen Shot 2019-03-31 at 10 58 52 PM" src="https://user-images.githubusercontent.com/19575682/55301155-111c0a80-5409-11e9-9168-c4e1c7c4c048.png">

**Comment by reardenlife** [comment]
@Pancho111

1.) First and third screenshot - remove the first line.  The script should start with #
2.) Second screenshot - add the ending } to make it a valid json file
3.) Do not forget to put executable flag on bash files ( chmod +x *.sh )
4.) You have to provide a link on PLAYLIST, not an album

**Comment by Pancho111** [comment]
> @Pancho111
> 
> 1.) First and third screenshot - remove the first line. The script should start with #
> 2.) Second screenshot - add the ending } to make it a valid json file
> 3.) Do not forget to put executable flag on bash files ( chmod +x *.sh )
> 4.) You have to provide a link on PLAYLIST, not an album

Hi Reardenlife , 
I have everything fine now ,but spotify-get-covers is giving me not found for some reason 
<img width="730" alt="Screen Shot 2019-04-01 at 1 07 36 AM" src="https://user-images.githubusercontent.com/19575682/55304705-cc00d400-541a-11e9-9478-ef7bc956e605.png">
This is my folder with the music 
and this is the file .. can you please check it to see if I am missing something  
I am sorry to bother you too much 

<img width="727" alt="Screen Shot 2019-04-01 at 1 06 56 AM" src="https://user-images.githubusercontent.com/19575682/55304726-edfa5680-541a-11e9-9716-31695b682dbf.png">

By the way  spotify-hlp-get-covers is working fine.

Thanks
Thanks

**Comment by reardenlife** [comment]
@Pancho111
> "but spotify-get-covers is giving me not found for some reason"

It would be really nice to get the exact text of the error.

**Comment by durandom** [comment]
@reardenlife jfyi: https://github.com/wolfmanx/spotify-ripper/tree/pr-collect has a `--large-album-cover` option that works. You need to export the web api credentials at the top of the README though.
So, basically applying [this](https://gist.github.com/durandom/255f4e2b2164228f727cb3a281b8517b) and the large album option fixes it...

**Comment by seandex** [comment]
> @reardenlife jfyi: https://github.com/wolfmanx/spotify-ripper/tree/pr-collect has a `--large-album-cover` option that works. You need to export the web api credentials at the top of the README though.
> So, basically applying [this](https://gist.github.com/durandom/255f4e2b2164228f727cb3a281b8517b) and the large album option fixes it...

I just re-compiled it with vikbez but gets the token error. I didn't do the web api creds, because I usually rsync .config folder, should I re-do the web api credentials? I can rip just can't cover art.

EDIT: I tried that remove-from-playlist, however, i get invalid user error, it just doesn't work. or manuals are not detail. I tested similar node app.js my credential, app id, and the key works fine. i don't like ubuntu it just doenst work. my hours for nothing again.
did you confirm this work?

INVALID_CLIENT: Invalid redirect URI

**Comment by Pancho111** [comment]
> > @reardenlife jfyi: https://github.com/wolfmanx/spotify-ripper/tree/pr-collect has a `--large-album-cover` option that works. You need to export the web api credentials at the top of the README though.
> > So, basically applying [this](https://gist.github.com/durandom/255f4e2b2164228f727cb3a281b8517b) and the large album option fixes it...
> 
> I just re-compiled it with vikbez but gets the token error. I didn't do the web api creds, because I usually rsync .config folder, should I re-do the web api credentials? I can rip just can't cover art.
> 
> EDIT: I tried that remove-from-playlist, however, i get invalid user error, it just doesn't work. or manuals are not detail. I tested similar node app.js my credential, app id, and the key works fine. i don't like ubuntu it just doenst work. my hours for nothing again.
> did you confirm this work?
> 
> INVALID_CLIENT: Invalid redirect URI
HI seandex
Did you finally get it to work ?
I haven't , 
I have a macbook pro.
please let me know if you got it work ,how did you do it ?
thanks

**Comment by Pancho111** [comment]
> 
> 
> @reardenlife jfyi: https://github.com/wolfmanx/spotify-ripper/tree/pr-collect has a `--large-album-cover` option that works. You need to export the web api credentials at the top of the README though.
> So, basically applying [this](https://gist.github.com/durandom/255f4e2b2164228f727cb3a281b8517b) and the large album option fixes it...



> 
> 
> @reardenlife jfyi: https://github.com/wolfmanx/spotify-ripper/tree/pr-collect has a `--large-album-cover` option that works. You need to export the web api credentials at the top of the README though.
> So, basically applying [this](https://gist.github.com/durandom/255f4e2b2164228f727cb3a281b8517b) and the large album option fixes it...

Hi durandom,
I could not get it to work , look all I want is the script to download the artwork , I really don't care about the playlist thing .
If you can show me how to fix this issue I will appreciate it too much .
Thanks

**Comment by reardenlife** [comment]
Let me clarify the things once and for all.

@Pancho111
> ", look all I want is"

<b>We do not care about what you want.</b>

**Comment by seandex** [comment]
> @reardenlife jfyi: https://github.com/wolfmanx/spotify-ripper/tree/pr-collect has a `--large-album-cover` option that works. You need to export the web api credentials at the top of the README though.
> So, basically applying [this](https://gist.github.com/durandom/255f4e2b2164228f727cb3a281b8517b) and the large album option fixes it...

@durandom do you have the working version on you?
