### ISSUE TITLE
Problem with naming in Python 3.9

### ISSUE THREAD

**Issue by ekisiel97** [hbashton/spotify-ripper#66]
Using Python 3.9, the following error will appear

    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner self.run()
    File "/home/user/.local/lib/python3.9/site-packages/spotify_ripper/eventloop.py", line 78, in run
    while self._runnable and self._ripper.isAlive():
    AttributeError: "Ripper" object has no attribute "isAlive"

This is due to the fact that the inheritance of the Thread class from the threading has renamed the attribute `isAlive()` to `is_alive()`.

This is easily fixed by changing the three files `main.py`, `eventloop.py` and `ripper.py` which each have exactly one instance of the `isAlive` attribute being referenced. This took me a while to find so hopefully for those who run into this in the future encounter this problem can fix it from this.

**Comment by tmaier** [comment]
Hi, can you provide a pull request?
