### ISSUE TITLE
'spotify.utils' has no attribute 'IntEnum'

### ISSUE THREAD

**Issue by nickberto** [hbashton/spotify-ripper#67]
Hello everyone,

does anyone has a clue how to solve this error?

File "/usr/local/lib/python3.9/site-packages/spotify_ripper-2.9.6-py3.9.egg/spotify_ripper/ripper.py", line 34, in <module>
    class BitRate(spotify.utils.IntEnum):
AttributeError: module 'spotify.utils' has no attribute 'IntEnum'

Thanks and best regards,
Nick

**Comment by richardk80** [comment]
That error is most likely because you're trying to use spotify-ripper with Python 3 when you should be using it with Python 2.

**Comment by nickberto** [comment]
Essentially, I was missing the libspotify.so on my PC, there is no limitation to use spotify-ripper just with python 2
