### ISSUE TITLE
spotify.error.Timeout: Operation did not complete in 10.000s

### ISSUE THREAD

**Issue by jp1995** [hbashton/spotify-ripper#8]
I've tried running as root and reinstalling, without success.

These are the errors I'm getting when running spotify-ripper -u username URI:

```
Loading playlist...
Exception in thread SpotifyRipperThread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/site-packages/spotify_ripper-2.9.1-py3.5.egg/spotify_ripper/ripper.py", line 223, in run
    tracks = list(get_tracks_from_uri(uri))
  File "/usr/lib/python3.5/site-packages/spotify_ripper-2.9.1-py3.5.egg/spotify_ripper/ripper.py", line 218, in get_tracks_from_uri
    return self.load_link(uri)
  File "/usr/lib/python3.5/site-packages/spotify_ripper-2.9.1-py3.5.egg/spotify_ripper/ripper.py", line 431, in load_link
    self.current_playlist.load()
  File "/usr/lib/python3.5/site-packages/pyspotify-2.0.5-py3.5-linux-x86_64.egg/spotify/playlist.py", line 118, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python3.5/site-packages/pyspotify-2.0.5-py3.5-linux-x86_64.egg/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
spotify.error.Timeout: Operation did not complete in 10.000s
```

Not sure how to proceed

**Comment by jp1995** [comment]
Well, this is silly.

This only happens when ripping the official Discover Weekly playlist created by Spotify.

The workaround is easy, just save the playlist as your own and rip that.

**Comment by simar7** [comment]
Also ran into the same issue. Workaround works.

**Comment by apps9999** [comment]
How do you save playlist as your own ? Never could get any playlist download working yet.
sudo spotify-ripper -u username spotify:user:username:playlist:URI

**Comment by pabx06** [comment]
i would like to add support for the web api :  developer.spotify.com/web-api/console/get-playlist/
but i dont how & where to do it

`
GET /v1/users/spotify/playlists/37i9dQZF1DWWGyg7tl2Dae?market=ES HTTP/1.1
Host: api.spotify.com
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, deflate, compress
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
User-Agent: Spotify API Console v0.1
`

`
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Access-Control-Max-Age: 604800
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Transfer-Encoding: chunked
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=31536000
Keep-Alive: timeout=600
Server: nginx
Connection: keep-alive
Etag: "4b97c3768b923b70e1f9a8b6b53dcc2a"
Cache-Control: public, max-age=0
Date: Wed, 01 Nov 2017 02:14:41 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Content-Type: application/json; charset=utf-8
`

or even easier : retriveonly tracks uri of playlist:

`GET /v1/users/spotify/playlists/37i9dQZF1DWWGyg7tl2Dae?market=ES&fields=tracks.items.track.uri HTTP/1.1
Host: api.spotify.com
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, deflate, compress
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
User-Agent: Spotify API Console v0.1`

'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Access-Control-Max-Age: 604800
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Transfer-Encoding: chunked
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=31536000
Keep-Alive: timeout=600
Server: nginx
Connection: keep-alive
Etag: "e4856ebe54589de854175d75336b7af8"
Cache-Control: public, max-age=0
Date: Wed, 01 Nov 2017 02:25:42 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Content-Type: application/json; charset=utf-8
`

data response:

`
{
  "tracks" : {
    "items" : [ {
      "track" : {
        "uri" : "spotify:track:4xlxojOaZyOQi7P8ig1BvH"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:56LbBPU6EfIGKqSIpWNrTw"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:22rwhHmnh9ve1pBqas9p0q"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:15ldEtpmRo0wfmOhtxZc20"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:5Rd2mJtULMR7DpHhaz8Q0t"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:4hLvUbH5dkCByoNFsM02Js"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:0v94bkWX5NUtTN7OpCcA19"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:5mGxQUIVcP37KegJZxaZaa"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:2LqkSIhAaLJgNMGenDawhK"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:1EruLdYjT2ejexupvbq6w5"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:7Gg3vweZopSn1QBEvM8YSF"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:1cD7C2muyWQopCkEJ8YM6O"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:3CPsPpLW6vwrgGX9qPxoPs"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:1Z5gM4r4V0W6Lct3k27Pwi"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:2A5B1CWkYwI5rPa17SkJ4A"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:4epgC84jqVTZddr2gRklSN"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:3DayGAKO98iqpDOCtNQ0AK"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:0NuJFB16j54ZDp6Z0U1pr4"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:3W3DQFt8UkFBpX030OCLg9"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:0DoDAp86dHuaCnmdIQ8dTi"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:4fKAPa1mPoF0fE3C5tqQ2t"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:2Cv8fs0SPLX1XaLQ80Lvds"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:587TweVWXecNbslAyhqyPq"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:1XYMXpp3p2gWcpEdBikQqJ"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:5PCKCffFrcyUvnhxJoPlK2"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:3j5hiaEtn22AJyz4ugwckH"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:2tZPDI0h4ccXDsd0TsZYo2"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:5Nb6txEq65b9UfeplVF2a8"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:15WLV5IYMk2ZFsNzJjJFlI"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:0auniS70iWb5lXTdvXrVaq"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:6Tg12y7yHaFPNVgjQROO9j"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:4GpKrkap009T7N76Z5LpwI"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:1JxO4qw3kGPRPM6CAEAyCI"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:1SdZq0kGNVXHTVY5to8V4E"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:7tFlkl1WAI3c1n6wzAErUm"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:3k5V5abRZ43eFk2OzILv3D"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:6KjLPmm0DJQUtcZi5WnPu1"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:7bDIxtZAb4T4628gPgKojf"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:5crvmrPbAWy85OtZ5kcsVA"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:3l1Lj966Pr7NSj1YV99Dvw"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:1PbJURXhARPrUscW8dMxei"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:0W8oh1Zst7Y1GczYEDOIuS"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:6NcTKRtXWG6w5TSWnwMHGm"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:1kbwEcixFWVj5dFO9Kso3J"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:60snjZK3lWHNRt4doPT1NR"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:3v6ua4MwSNNBuAPXyc2LSB"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:29cq73YyctBzMjLZsAoKdb"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:6Fhc4STGOMa4ByDFpSTjBz"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:6uiVoZ65Gf98Wyeuf0NRZr"
      }
    }, {
      "track" : {
        "uri" : "spotify:track:5Qb8HgGZCAVKx1ic5iKyHu"
      }
    } ]
  }
}
`
